/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uncuyo.dbproyect.OLDgui;
import uncuyo.dbproyect.OLDgui.AgentsCUD_imp;
import javax.swing.JOptionPane;
import uncuyo.dbproyect.domain.Date;
import uncuyo.dbproyect.domain.PhoneNumber;
import uncuyo.dbproyect.domain.Mail;
/**
 *
 * @author Martín
 */
public class AgentsCUD extends javax.swing.JPanel {
    AgentsCUD_imp imp = new AgentsCUD_imp();
    /**
     * Creates new form AgentsManagement
     */
    public AgentsCUD() {
        initComponents();
        //Default disabled
        Delete_btn.setEnabled(false);
        
        CRole_txf.setEnabled(false);
        CCountry_txf.setEnabled(false);
        CState_txf.setEnabled(false);
        CZone_txf.setEnabled(false);
        
        UCountry_txf.setEnabled(false);
        UState_txf.setEnabled(false);
        UZone_txf.setEnabled(false);
        UName_txf.setEnabled(false);
        UCountry_Box.setEnabled(false);
        UState_Box.setEnabled(false);
        UZone_Box.setEnabled(false);
        ULastName_txf.setEnabled(false);
        UBornDate_formatted.setEnabled(false);
        this.UNationalNumber_formatted.setEnabled(false);
        this.URole_txf.setEnabled(false);
        this.URole_List.setEnabled(false);
        this.URole_Box.setEnabled(false);
        this.UCountry_List.setEnabled(false);
        this.UState_List.setEnabled(false);
        this.UZone_List.setEnabled(false);
        this.UStreet_txf.setEnabled(false);
        this.UNumber_txf.setEnabled(false);
        this.UHealthEnsurance_txf.setEnabled(false);
        this.UEmergencyPhone_formatted.setEnabled(false);
        this.UphoneNumber_formatted.setEnabled(false);
        this.Umail_formatted.setEnabled(false);
        //Combo box models
        imp.SetRoleComboBoxModel(CRole_List);
        imp.SetCountryComboBoxModel(CCountry_List);
        imp.SetStateComboBoxModel(CState_List);
        imp.SetZoneComboBoxModel(CZone_List);
        
        imp.SetRoleComboBoxModel(URole_List);
        imp.SetCountryComboBoxModel(UCountry_List);
        imp.SetStateComboBoxModel(UState_List);
        imp.SetZoneComboBoxModel(UZone_List);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        CUDtab = new javax.swing.JTabbedPane();
        PaneDelete = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Did_txf = new javax.swing.JTextField();
        Delete_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DStatus_txf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Unsuscribe_btn = new javax.swing.JButton();
        DSecure_box = new javax.swing.JCheckBox();
        PaneUpdate = new javax.swing.JPanel();
        Update_btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Uid_txf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Umail_formatted = new javax.swing.JFormattedTextField();
        UphoneNumber_formatted = new javax.swing.JFormattedTextField();
        UPhone_Box = new javax.swing.JCheckBox();
        UMail_Box = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        UHealthEnsurance_txf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        UEmergencyPhone_formatted = new javax.swing.JFormattedTextField();
        UEmergencyPhone_Box = new javax.swing.JCheckBox();
        UHealth_Box = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        UStreet_txf = new javax.swing.JTextField();
        UNumber_txf = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        URole_Box = new javax.swing.JCheckBox();
        URole_List = new javax.swing.JComboBox<>();
        URole_txf = new javax.swing.JTextField();
        URole_Box2 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        UStatus_txf = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        UName_txf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        UBornDate_formatted = new javax.swing.JFormattedTextField();
        UNationalNumber_formatted = new javax.swing.JFormattedTextField();
        ULastName_txf = new javax.swing.JTextField();
        UName_Box = new javax.swing.JCheckBox();
        ULastName_Box = new javax.swing.JCheckBox();
        UBornDate_Box = new javax.swing.JCheckBox();
        UNationalID_Box = new javax.swing.JCheckBox();
        UAddress_Box = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        UZone_List = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        UState_List = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        UCountry_List = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        UCountry_Box = new javax.swing.JCheckBox();
        UZone_Box = new javax.swing.JCheckBox();
        UState_Box = new javax.swing.JCheckBox();
        UCountry_txf = new javax.swing.JTextField();
        UState_txf = new javax.swing.JTextField();
        UZone_txf = new javax.swing.JTextField();
        PaneCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Create_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CZone_List = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CState_List = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CCountry_List = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CCountry_Box = new javax.swing.JCheckBox();
        CZone_Box = new javax.swing.JCheckBox();
        CState_Box = new javax.swing.JCheckBox();
        CCountry_txf = new javax.swing.JTextField();
        CState_txf = new javax.swing.JTextField();
        CZone_txf = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        CStreet_txf = new javax.swing.JTextField();
        CNumber_txf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CRole_Box = new javax.swing.JCheckBox();
        CRole_txf = new javax.swing.JTextField();
        CRole_List = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CName_txf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CBornDate_formatted = new javax.swing.JFormattedTextField();
        CNationalNumber_formatted = new javax.swing.JFormattedTextField();
        CLastName_txf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        CHealthEnsurance_txf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CEmergencyPhone_formatted = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CMail_formatted = new javax.swing.JFormattedTextField();
        CPhoneNumber_formatted = new javax.swing.JFormattedTextField();
        CStatus_txf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Agent ID to Delete or Unsuscribe:");

        Did_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Did_txfActionPerformed(evt);
            }
        });

        Delete_btn.setText("Delete Agent");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        jLabel4.setText("All Information Related to the Agent will be Deleted too.");

        DStatus_txf.setText("-");

        jLabel16.setText("RESULT:");

        Unsuscribe_btn.setText("Unsuscribe");
        Unsuscribe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unsuscribe_btnActionPerformed(evt);
            }
        });

        DSecure_box.setText("I'm sure i want to Delete an Agent");
        DSecure_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSecure_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaneDeleteLayout = new javax.swing.GroupLayout(PaneDelete);
        PaneDelete.setLayout(PaneDeleteLayout);
        PaneDeleteLayout.setHorizontalGroup(
            PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneDeleteLayout.createSequentialGroup()
                        .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaneDeleteLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Did_txf)
                                .addGap(57, 57, 57))
                            .addGroup(PaneDeleteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(DStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneDeleteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Unsuscribe_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DSecure_box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_btn)
                        .addGap(8, 8, 8))))
        );
        PaneDeleteLayout.setVerticalGroup(
            PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneDeleteLayout.createSequentialGroup()
                        .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Did_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(PaneDeleteLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addGroup(PaneDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unsuscribe_btn)
                    .addComponent(Delete_btn)
                    .addComponent(DSecure_box))
                .addContainerGap())
        );

        CUDtab.addTab("Delete", PaneDelete);

        Update_btn.setText("Update Agent");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        jLabel17.setText("Update by ID:");

        Uid_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uid_txfActionPerformed(evt);
            }
        });

        jLabel22.setText("Phone number:");

        jLabel23.setText("Mail");

        Umail_formatted.setText("noseque@gmail.com");

        UphoneNumber_formatted.setText("2839289283");

        UPhone_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPhone_BoxActionPerformed(evt);
            }
        });

        UMail_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMail_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(UphoneNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(Umail_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UPhone_Box)
                    .addComponent(UMail_Box)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(UphoneNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UPhone_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Umail_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(UMail_Box)))
        );

        UHealthEnsurance_txf.setText("name");

        jLabel24.setText("Emergency Phone Number");

        jLabel25.setText("Health Ensurance Name");

        UEmergencyPhone_formatted.setText("92839283928");

        UEmergencyPhone_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UEmergencyPhone_BoxActionPerformed(evt);
            }
        });

        UHealth_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UHealth_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(UHealthEnsurance_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(UEmergencyPhone_formatted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UEmergencyPhone_Box, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UHealth_Box, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(UHealthEnsurance_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UHealth_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(UEmergencyPhone_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UEmergencyPhone_Box))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel26.setText("Live in Street ");

        UStreet_txf.setText("Main Street");

        UNumber_txf.setText("Number");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(3, 3, 3)
                .addComponent(UStreet_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UNumber_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UStreet_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UNumber_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(29, 29, 29))
        );

        URole_Box.setText("Create new Role");
        URole_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URole_BoxActionPerformed(evt);
            }
        });

        URole_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        URole_txf.setText("new Role");

        URole_Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URole_Box2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(URole_Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URole_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(URole_Box2)
                .addGap(30, 30, 30))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(URole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(URole_Box)
                .addComponent(URole_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(URole_Box2)
        );

        UStatus_txf.setText("-");
        UStatus_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UStatus_txfActionPerformed(evt);
            }
        });

        jLabel36.setText("RESULT:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(UStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel32.setText("Last Name:");

        jLabel33.setText("Born Date:");

        jLabel34.setText("National ID:");

        UName_txf.setText("name");

        jLabel35.setText("Name:");

        UBornDate_formatted.setText("00/00/00");

        UNationalNumber_formatted.setText("43.222.222");

        ULastName_txf.setText("lastname");

        UName_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UName_BoxActionPerformed(evt);
            }
        });

        ULastName_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULastName_BoxActionPerformed(evt);
            }
        });

        UBornDate_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBornDate_BoxActionPerformed(evt);
            }
        });

        UNationalID_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNationalID_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UName_txf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ULastName_txf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UBornDate_formatted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UNationalNumber_formatted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UName_Box)
                    .addComponent(ULastName_Box)
                    .addComponent(UNationalID_Box)
                    .addComponent(UBornDate_Box))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UName_Box, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(ULastName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ULastName_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(UBornDate_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UNationalID_Box))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(UBornDate_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(UNationalNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UAddress_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UAddress_BoxActionPerformed(evt);
            }
        });

        UZone_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Godoy Cruz" }));

        jLabel8.setText("Zone:");

        UState_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mendoza" }));

        jLabel9.setText("State:");

        UCountry_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina" }));

        jLabel27.setText("Country:");

        UCountry_Box.setText("new Country");
        UCountry_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UCountry_BoxMousePressed(evt);
            }
        });

        UZone_Box.setText("new Zone");
        UZone_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UZone_BoxMousePressed(evt);
            }
        });

        UState_Box.setText("new State");
        UState_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UState_BoxMousePressed(evt);
            }
        });

        UCountry_txf.setText("Argentina2");
        UCountry_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UCountry_txfActionPerformed(evt);
            }
        });

        UState_txf.setText("Mendoza2");
        UState_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UState_txfActionPerformed(evt);
            }
        });

        UZone_txf.setText("Godoy Cruz2");
        UZone_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UZone_txfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UCountry_Box))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(UCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UState_Box))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(UState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(UZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UZone_Box)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(UCountry_Box)
                    .addComponent(UZone_Box)
                    .addComponent(UState_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PaneUpdateLayout = new javax.swing.GroupLayout(PaneUpdate);
        PaneUpdate.setLayout(PaneUpdateLayout);
        PaneUpdateLayout.setHorizontalGroup(
            PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneUpdateLayout.createSequentialGroup()
                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                        .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PaneUpdateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Uid_txf, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaneUpdateLayout.createSequentialGroup()
                                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UAddress_Box))
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneUpdateLayout.createSequentialGroup()
                                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115))
                                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addComponent(Update_btn)
                                .addGap(44, 44, 44)))))
                .addContainerGap())
        );
        PaneUpdateLayout.setVerticalGroup(
            PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneUpdateLayout.createSequentialGroup()
                        .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Uid_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UAddress_Box))
                .addGap(2, 2, 2)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PaneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CUDtab.addTab("Update", PaneUpdate);

        jLabel1.setText("Create a new Agent:");

        Create_btn.setText("Create Agent");
        Create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_btnActionPerformed(evt);
            }
        });

        CZone_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Godoy Cruz" }));

        jLabel7.setText("Zone:");

        CState_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mendoza" }));

        jLabel6.setText("State:");

        CCountry_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina" }));

        jLabel5.setText("Country:");

        CCountry_Box.setText("new Country");
        CCountry_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CCountry_BoxMousePressed(evt);
            }
        });

        CZone_Box.setText("new Zone");
        CZone_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CZone_BoxMousePressed(evt);
            }
        });

        CState_Box.setText("new State");
        CState_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CState_BoxMousePressed(evt);
            }
        });

        CCountry_txf.setText("Argentina");
        CCountry_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCountry_txfActionPerformed(evt);
            }
        });

        CState_txf.setText("Mendoza");
        CState_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CState_txfActionPerformed(evt);
            }
        });

        CZone_txf.setText("Godoy Cruz");
        CZone_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CZone_txfActionPerformed(evt);
            }
        });

        jLabel10.setText("Live on Street:");

        CStreet_txf.setText("Renato Zanzin");

        CNumber_txf.setText("2049");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CStreet_txf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CNumber_txf)
                .addGap(214, 214, 214))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CStreet_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNumber_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCountry_Box))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CState_Box))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CZone_Box)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(CCountry_Box)
                    .addComponent(CZone_Box)
                    .addComponent(CState_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CRole_Box.setText("Create new Role");
        CRole_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CRole_BoxMousePressed(evt);
            }
        });

        CRole_txf.setText("Student");
        CRole_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRole_txfActionPerformed(evt);
            }
        });

        CRole_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CRole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CRole_txf, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CRole_Box)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CRole_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CRole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CRole_Box))
        );

        jLabel18.setText("Last Name:");

        jLabel19.setText("Born Date:");

        jLabel20.setText("National ID:");

        CName_txf.setText("Martin");

        jLabel21.setText("Name:");

        CBornDate_formatted.setText("04/08/2001");

        CNationalNumber_formatted.setText("43.636.917");

        CLastName_txf.setText("Cogo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CLastName_txf)
                    .addComponent(CNationalNumber_formatted, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBornDate_formatted, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CName_txf))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CLastName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CBornDate_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(CNationalNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        CHealthEnsurance_txf.setText("DAMSU");

        jLabel12.setText("Emergency Phone Number");

        jLabel11.setText("Health Ensurance Name");

        CEmergencyPhone_formatted.setText("+261 9 428 7968");
        CEmergencyPhone_formatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEmergencyPhone_formattedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CEmergencyPhone_formatted, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(CHealthEnsurance_txf))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CHealthEnsurance_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CEmergencyPhone_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel13.setText("Phone number:");

        jLabel14.setText("Mail");

        CMail_formatted.setText("martincogo4@gmail.com");

        CPhoneNumber_formatted.setText("+261 5 437 3741");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CPhoneNumber_formatted))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(CMail_formatted, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CPhoneNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMail_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CStatus_txf.setText("-");

        jLabel15.setText("RESULT:");

        javax.swing.GroupLayout PaneCreateLayout = new javax.swing.GroupLayout(PaneCreate);
        PaneCreate.setLayout(PaneCreateLayout);
        PaneCreateLayout.setHorizontalGroup(
            PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneCreateLayout.createSequentialGroup()
                        .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneCreateLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(20, 20, 20))
                    .addGroup(PaneCreateLayout.createSequentialGroup()
                        .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaneCreateLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Create_btn))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        PaneCreateLayout.setVerticalGroup(
            PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneCreateLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneCreateLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PaneCreateLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PaneCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Create_btn)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        CUDtab.addTab("Create ", PaneCreate);

        add(CUDtab, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void Create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_btnActionPerformed
        // TODO add your handling code here:
        try{
            String Role;
            String Country;
            String State;
            String Zone;
            if(CRole_Box.isSelected()){
                Role = CRole_txf.getText();
            }else{
                Role =(String) CRole_List.getSelectedItem();
            }
            if(CCountry_Box.isSelected()){
                Country = CCountry_txf.getText();
            }else{
                Country =(String) CCountry_List.getSelectedItem();
            }
            if(CState_Box.isSelected()){
                State = CState_txf.getText();
            }else{
                State =(String) CState_List.getSelectedItem();
            }
            if(CZone_Box.isSelected()){
                Zone = CZone_txf.getText();
            }else{
                Zone =(String) CZone_List.getSelectedItem();
            }
            imp.Create( Role, CName_txf.getText(), CLastName_txf.getText(),CBornDate_formatted.getText(), CNationalNumber_formatted.getText(), Country,State, Zone, CStreet_txf.getText(), CNumber_txf.getText(), CHealthEnsurance_txf.getText(), CEmergencyPhone_formatted.getText(),CPhoneNumber_formatted.getText(),CMail_formatted.getText());
            CStatus_txf.setText("Succed.Agent Create");
        }catch(Exception e){
            CStatus_txf.setText("Error.Agent not Create");
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_Create_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        // TODO add your handling code here:
        try{
            imp.Delete(Integer.parseInt(Did_txf.getText().strip()));
            DStatus_txf.setText("Succed.Agent Deleted");
        }catch(Exception e){
            DStatus_txf.setText("Error.Agent not deleted");
             JOptionPane.showMessageDialog(jDialog1, e.getMessage());  
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        // TODO add your handling code here:
        int id =Integer.parseInt(Uid_txf.getText());
        try{
            if(this.UName_Box.isSelected()){
                imp.UpdateName(id,UName_txf.getText());
            }
            if(this.ULastName_Box.isSelected()){
                imp.UpdateLastName(id,ULastName_txf.getText());
            }
            if(this.UBornDate_Box.isSelected()){
                imp.UpdateBornDate(id,new Date(UBornDate_formatted.getText()));
            }
            if(this.UNationalID_Box.isSelected()){
                imp.UpdateNationalNumber(id,this.UNationalNumber_formatted.getText());
            }
            if(URole_Box2.isSelected()){
                if(URole_Box.isSelected()){
                    imp.UpdateRole(id,this.URole_txf.getText());
                }else{
                    imp.UpdateRole(id,(String) URole_List.getSelectedItem());
                }
            }
            if(this.UAddress_Box.isSelected()){
                String country;
                String state;
                String zone;
                if(this.UCountry_Box.isSelected()){
                    country = this.UCountry_txf.getText();
                }else{
                    country = (String) this.UCountry_List.getSelectedItem();
                }
                if(this.UState_Box.isSelected()){
                   state = this.UState_txf.getText();
                }else{
                    state = (String) this.UState_List.getSelectedItem();
                }
                if(this.UZone_Box.isSelected()){
                    zone = this.UZone_txf.getText();
                }else{
                    zone = (String) this.UZone_List.getSelectedItem();
                }
                imp.UpdateAddress(id,country,state,zone,this.UStreet_txf.getText(),this.UNumber_txf.getText());
            }
            if(this.UHealth_Box.isSelected()){
                imp.UpdateHealth(id,UHealthEnsurance_txf.getText());
            }
            if(this.UEmergencyPhone_Box.isSelected()){
                imp.UpdateEmergencyPhone(id,new PhoneNumber(UEmergencyPhone_formatted.getText()));
            }
            if(this.UPhone_Box.isSelected()){
                imp.UpdatePhone(id,new PhoneNumber(UphoneNumber_formatted.getText()));
            }
            if(this.UMail_Box.isSelected()){
                imp.UpdateMail(id,new Mail(Umail_formatted.getText()));
            }
            UStatus_txf.setText("Succed.Agent Updated");
        }catch(Exception e){
            UStatus_txf.setText("Error.Agent Not Updated");
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void CRole_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CRole_BoxMousePressed
    // TODO add your handling code here:
    if(CRole_Box.isSelected()){
       CRole_txf.setEnabled(false);
       CRole_List.setEnabled(true);
    }else{
        CRole_txf.setEnabled(true);
        CRole_List.setEnabled(false);
    }
    }//GEN-LAST:event_CRole_BoxMousePressed

    private void UName_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UName_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UName_Box.isSelected()){
       this.UName_txf.setEnabled(true);
    }else{
        UName_txf.setEnabled(false);
    }
    }//GEN-LAST:event_UName_BoxActionPerformed

    private void ULastName_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULastName_BoxActionPerformed
        // TODO add your handling code here:
    if(this.ULastName_Box.isSelected()){
       this.ULastName_txf.setEnabled(true);
    }else{
        ULastName_txf.setEnabled(false);
    }
    }//GEN-LAST:event_ULastName_BoxActionPerformed

    private void UBornDate_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBornDate_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UBornDate_Box.isSelected()){
       this.UBornDate_formatted.setEnabled(true);
    }else{
        UBornDate_formatted.setEnabled(false);
    }
    }//GEN-LAST:event_UBornDate_BoxActionPerformed

    private void UNationalID_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNationalID_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UNationalID_Box.isSelected()){
       this.UNationalNumber_formatted.setEnabled(true);
    }else{
        UNationalNumber_formatted.setEnabled(false);
    }
    }//GEN-LAST:event_UNationalID_BoxActionPerformed

    private void URole_Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URole_Box2ActionPerformed
        // TODO add your handling code here:
    if(URole_Box2.isSelected()){
       this.URole_List.setEnabled(true);
       this.URole_txf.setEnabled(false);
       this.URole_Box.setEnabled(true);
    }else{
        this.URole_List.setEnabled(false);
        this.URole_txf.setEnabled(false);
        this.URole_Box.setEnabled(false);
    }
    }//GEN-LAST:event_URole_Box2ActionPerformed

    private void UAddress_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UAddress_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UAddress_Box.isSelected()){
       this.UCountry_List.setEnabled(true);
       this.UState_List.setEnabled(true);
       this.UZone_List.setEnabled(true);
       this.UStreet_txf.setEnabled(true);
       this.UNumber_txf.setEnabled(true);
       this.UCountry_Box.setEnabled(true);
       this.UState_Box.setEnabled(true);
       this.UZone_Box.setEnabled(true);
    }else{
        this.UCountry_List.setEnabled(false);
       this.UState_List.setEnabled(false);
       this.UZone_List.setEnabled(false);
       this.UStreet_txf.setEnabled(false);
       this.UNumber_txf.setEnabled(false);
       this.UCountry_Box.setEnabled(false);
       this.UState_Box.setEnabled(false);
       this.UZone_Box.setEnabled(false);
    }
    }//GEN-LAST:event_UAddress_BoxActionPerformed

    private void UHealth_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UHealth_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UHealth_Box.isSelected()){
       this.UHealthEnsurance_txf.setEnabled(true);
    }else{
       this.UHealthEnsurance_txf.setEnabled(false);
    }
    }//GEN-LAST:event_UHealth_BoxActionPerformed

    private void UEmergencyPhone_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UEmergencyPhone_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UEmergencyPhone_Box.isSelected()){
        this.UEmergencyPhone_formatted.setEnabled(true);
    }else{
        this.UEmergencyPhone_formatted.setEnabled(false);
    }
    }//GEN-LAST:event_UEmergencyPhone_BoxActionPerformed

    private void UPhone_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPhone_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UPhone_Box.isSelected()){
       this.UphoneNumber_formatted.setEnabled(true);
    }else{
       this.UphoneNumber_formatted.setEnabled(false);
    }
    }//GEN-LAST:event_UPhone_BoxActionPerformed

    private void UMail_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMail_BoxActionPerformed
        // TODO add your handling code here:
    if(this.UMail_Box.isSelected()){
        this.Umail_formatted.setEnabled(true);
    }else{
        this.Umail_formatted.setEnabled(false);
    }
    }//GEN-LAST:event_UMail_BoxActionPerformed

    private void URole_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URole_BoxActionPerformed
        // TODO add your handling code here:
     if(URole_Box.isSelected()){
       URole_txf.setEnabled(true);
       URole_List.setEnabled(false);
    }else{
        URole_txf.setEnabled(false);
        URole_List.setEnabled(true);
    }   
    }//GEN-LAST:event_URole_BoxActionPerformed

    private void CRole_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRole_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CRole_txfActionPerformed

    private void Uid_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uid_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uid_txfActionPerformed

    private void CEmergencyPhone_formattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEmergencyPhone_formattedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEmergencyPhone_formattedActionPerformed

    private void CCountry_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCountry_BoxMousePressed
        // TODO add your handling code here:
    if(CCountry_Box.isSelected()){
       CCountry_txf.setEnabled(false);
       CCountry_List.setEnabled(true);
       CZone_txf.setEnabled(false);
       CZone_List.setEnabled(true);
    }else{
        CCountry_txf.setEnabled(true);
        CCountry_List.setEnabled(false);
        CZone_txf.setEnabled(true);
        CZone_List.setEnabled(false);
        CState_txf.setEnabled(true);
        CState_List.setEnabled(false);
        CState_txf.setEnabled(false);
        CState_List.setEnabled(true);
    }
    }//GEN-LAST:event_CCountry_BoxMousePressed

    private void CZone_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CZone_BoxMousePressed
        // TODO add your handling code here:
    if(CZone_Box.isSelected()){
       CZone_txf.setEnabled(false);
       CZone_List.setEnabled(true);
    }else{
        CZone_txf.setEnabled(true);
        CZone_List.setEnabled(false);
    }
    }//GEN-LAST:event_CZone_BoxMousePressed

    private void CState_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CState_BoxMousePressed
        // TODO add your handling code here:
    if(CState_Box.isSelected()){
       CState_txf.setEnabled(false);
       CState_List.setEnabled(true);
       CZone_txf.setEnabled(false);
       CZone_List.setEnabled(true);
    }else{
        CState_txf.setEnabled(true);
        CState_List.setEnabled(false);
        CZone_txf.setEnabled(true);
        CZone_List.setEnabled(false);
    }
    }//GEN-LAST:event_CState_BoxMousePressed

    private void CCountry_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCountry_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCountry_txfActionPerformed

    private void CState_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CState_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CState_txfActionPerformed

    private void CZone_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CZone_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CZone_txfActionPerformed

    private void UCountry_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCountry_BoxMousePressed
        // TODO add your handling code here:
    if(UCountry_Box.isSelected()){
       UCountry_txf.setEnabled(false);
       UCountry_List.setEnabled(true);
       UZone_txf.setEnabled(false);
       UZone_List.setEnabled(true);
       UState_txf.setEnabled(false);
        UState_List.setEnabled(true);
    }else{
        UCountry_txf.setEnabled(true);
        UCountry_List.setEnabled(false);
        UZone_txf.setEnabled(true);
        UZone_List.setEnabled(false);
        UState_txf.setEnabled(true);
        UState_List.setEnabled(false);
    }
    }//GEN-LAST:event_UCountry_BoxMousePressed

    private void UZone_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UZone_BoxMousePressed
        // TODO add your handling code here:
    if(UZone_Box.isSelected()){
       UZone_txf.setEnabled(false);
       UZone_List.setEnabled(true);
    }else{
        UZone_txf.setEnabled(true);
        UZone_List.setEnabled(false);
    }
    }//GEN-LAST:event_UZone_BoxMousePressed

    private void UState_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UState_BoxMousePressed
        // TODO add your handling code here:
    if(UState_Box.isSelected()){
        UState_txf.setEnabled(false);
        UState_List.setEnabled(true);
        UZone_txf.setEnabled(false);
       UZone_List.setEnabled(true);
    }else{
        UState_txf.setEnabled(true);
        UState_List.setEnabled(false);
        UZone_txf.setEnabled(true);
        UZone_List.setEnabled(false);
    }
    }//GEN-LAST:event_UState_BoxMousePressed

    private void UCountry_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UCountry_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UCountry_txfActionPerformed

    private void UState_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UState_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UState_txfActionPerformed

    private void UZone_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UZone_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UZone_txfActionPerformed

    private void UStatus_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UStatus_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UStatus_txfActionPerformed

    private void Unsuscribe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unsuscribe_btnActionPerformed
        // TODO add your handling code here:
        try{
            imp.Unsuscribe(Integer.parseInt(Did_txf.getText().strip()));
            DStatus_txf.setText("Succed.Agent unsuscribed");
        }catch(Exception e){
            DStatus_txf.setText("Error.Agent not unsuscribed");
             JOptionPane.showMessageDialog(jDialog1, e.getMessage());  
        }
    }//GEN-LAST:event_Unsuscribe_btnActionPerformed

    private void Did_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Did_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Did_txfActionPerformed

    private void DSecure_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSecure_boxActionPerformed
        // TODO add your handling code here:
    if(DSecure_box.isSelected()){
        Delete_btn.setEnabled(true);
    }else{
        Delete_btn.setEnabled(false);
    }
    }//GEN-LAST:event_DSecure_boxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CBornDate_formatted;
    private javax.swing.JCheckBox CCountry_Box;
    private javax.swing.JComboBox<String> CCountry_List;
    private javax.swing.JTextField CCountry_txf;
    private javax.swing.JFormattedTextField CEmergencyPhone_formatted;
    private javax.swing.JTextField CHealthEnsurance_txf;
    private javax.swing.JTextField CLastName_txf;
    private javax.swing.JFormattedTextField CMail_formatted;
    private javax.swing.JTextField CName_txf;
    private javax.swing.JFormattedTextField CNationalNumber_formatted;
    private javax.swing.JTextField CNumber_txf;
    private javax.swing.JFormattedTextField CPhoneNumber_formatted;
    private javax.swing.JCheckBox CRole_Box;
    private javax.swing.JComboBox<String> CRole_List;
    private javax.swing.JTextField CRole_txf;
    private javax.swing.JCheckBox CState_Box;
    private javax.swing.JComboBox<String> CState_List;
    private javax.swing.JTextField CState_txf;
    private javax.swing.JTextField CStatus_txf;
    private javax.swing.JTextField CStreet_txf;
    private javax.swing.JTabbedPane CUDtab;
    private javax.swing.JCheckBox CZone_Box;
    private javax.swing.JComboBox<String> CZone_List;
    private javax.swing.JTextField CZone_txf;
    private javax.swing.JButton Create_btn;
    private javax.swing.JCheckBox DSecure_box;
    private javax.swing.JTextField DStatus_txf;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTextField Did_txf;
    private javax.swing.JPanel PaneCreate;
    private javax.swing.JPanel PaneDelete;
    private javax.swing.JPanel PaneUpdate;
    private javax.swing.JCheckBox UAddress_Box;
    private javax.swing.JCheckBox UBornDate_Box;
    private javax.swing.JFormattedTextField UBornDate_formatted;
    private javax.swing.JCheckBox UCountry_Box;
    private javax.swing.JComboBox<String> UCountry_List;
    private javax.swing.JTextField UCountry_txf;
    private javax.swing.JCheckBox UEmergencyPhone_Box;
    private javax.swing.JFormattedTextField UEmergencyPhone_formatted;
    private javax.swing.JTextField UHealthEnsurance_txf;
    private javax.swing.JCheckBox UHealth_Box;
    private javax.swing.JCheckBox ULastName_Box;
    private javax.swing.JTextField ULastName_txf;
    private javax.swing.JCheckBox UMail_Box;
    private javax.swing.JCheckBox UName_Box;
    private javax.swing.JTextField UName_txf;
    private javax.swing.JCheckBox UNationalID_Box;
    private javax.swing.JFormattedTextField UNationalNumber_formatted;
    private javax.swing.JTextField UNumber_txf;
    private javax.swing.JCheckBox UPhone_Box;
    private javax.swing.JCheckBox URole_Box;
    private javax.swing.JCheckBox URole_Box2;
    private javax.swing.JComboBox<String> URole_List;
    private javax.swing.JTextField URole_txf;
    private javax.swing.JCheckBox UState_Box;
    private javax.swing.JComboBox<String> UState_List;
    private javax.swing.JTextField UState_txf;
    private javax.swing.JTextField UStatus_txf;
    private javax.swing.JTextField UStreet_txf;
    private javax.swing.JCheckBox UZone_Box;
    private javax.swing.JComboBox<String> UZone_List;
    private javax.swing.JTextField UZone_txf;
    private javax.swing.JTextField Uid_txf;
    private javax.swing.JFormattedTextField Umail_formatted;
    private javax.swing.JButton Unsuscribe_btn;
    private javax.swing.JButton Update_btn;
    private javax.swing.JFormattedTextField UphoneNumber_formatted;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
