/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uncuyo.dbproyect.OLDgui;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Martín
 */
public class AgentsSearch extends javax.swing.JPanel {
    AgentsSearch_imp imp = new AgentsSearch_imp();
    /**
     * Creates new form AdressManagement
     */
    public AgentsSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PredefinedSearch = new javax.swing.ButtonGroup();
        GlobalSearch = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        SAPane = new javax.swing.JPanel();
        SABornDate_Box = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SALook_Box = new javax.swing.JComboBox<>();
        SAName_Box = new javax.swing.JCheckBox();
        SALastName_Box = new javax.swing.JCheckBox();
        SARole_Box = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        SATable = new javax.swing.JTable();
        SAValue_txf = new javax.swing.JTextField();
        SANationalId_Box = new javax.swing.JCheckBox();
        SAHealth_Box = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        SAStreet_Box = new javax.swing.JCheckBox();
        SAZone_Box = new javax.swing.JCheckBox();
        SAState_Box = new javax.swing.JCheckBox();
        SACountry_Box = new javax.swing.JCheckBox();
        SASearch_bttn = new javax.swing.JButton();
        SAid_Box = new javax.swing.JCheckBox();
        SAMail_Box = new javax.swing.JCheckBox();
        SAEmergencyPhone_Box = new javax.swing.JCheckBox();
        SAPhone_Box = new javax.swing.JCheckBox();
        PSPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PSTable = new javax.swing.JTable();
        PSCountry_Rad = new javax.swing.JRadioButton();
        PSState_Rad = new javax.swing.JRadioButton();
        PSZone_Rad = new javax.swing.JRadioButton();
        PSGlobal_Rad = new javax.swing.JRadioButton();
        PSMail_Rad = new javax.swing.JRadioButton();
        SPSearch_bttn = new javax.swing.JButton();
        PSPhone_Rad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        SABornDate_Box.setText("Born Date");

        jLabel6.setText("Look for:");

        jLabel7.setText("Show:");

        SALook_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all Agents", "ID", "Role", "Name", "National ID Number", "Street", "Phone Number", "Mail" }));

        SAName_Box.setText("Name");

        SALastName_Box.setText("Last Name");

        SARole_Box.setText("Role");

        SATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(SATable);

        SANationalId_Box.setText("National ID");

        SAHealth_Box.setText("Health Ensurance Name");

        jLabel8.setText("Value:");

        SAStreet_Box.setText("Street");

        SAZone_Box.setText("Zone");

        SAState_Box.setText("State");

        SACountry_Box.setText("Country");

        SASearch_bttn.setText("Search");
        SASearch_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SASearch_bttnActionPerformed(evt);
            }
        });

        SAid_Box.setText("id");

        SAMail_Box.setText("Mail");

        SAEmergencyPhone_Box.setText("Emergency Phone");

        SAPhone_Box.setText("Phone");

        javax.swing.GroupLayout SAPaneLayout = new javax.swing.GroupLayout(SAPane);
        SAPane.setLayout(SAPaneLayout);
        SAPaneLayout.setHorizontalGroup(
            SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SAPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SAPaneLayout.createSequentialGroup()
                        .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SAEmergencyPhone_Box)
                            .addComponent(SAMail_Box)
                            .addComponent(SAHealth_Box)
                            .addComponent(SAPhone_Box)
                            .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAid_Box)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(SAName_Box)
                                .addComponent(SALastName_Box)
                                .addComponent(SARole_Box)
                                .addComponent(jLabel8)
                                .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SAValue_txf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SALook_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(SANationalId_Box)
                                .addComponent(SABornDate_Box)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SAPaneLayout.createSequentialGroup()
                                    .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SAZone_Box)
                                        .addComponent(SACountry_Box)
                                        .addComponent(SAState_Box)
                                        .addComponent(SAStreet_Box))
                                    .addGap(84, 84, 84))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                    .addGroup(SAPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SASearch_bttn)))
                .addContainerGap())
        );
        SAPaneLayout.setVerticalGroup(
            SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SAPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SAPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SAPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SASearch_bttn))
                    .addGroup(SAPaneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SALook_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(SAValue_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAid_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SARole_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAName_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SALastName_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SABornDate_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SANationalId_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAPhone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAMail_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAEmergencyPhone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAHealth_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SACountry_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAState_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAZone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAStreet_Box)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Serch by Agent Type", SAPane);

        PSTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(PSTable);

        PredefinedSearch.add(PSCountry_Rad);
        PSCountry_Rad.setText("Country List");

        PredefinedSearch.add(PSState_Rad);
        PSState_Rad.setText("State List");

        PredefinedSearch.add(PSZone_Rad);
        PSZone_Rad.setText("Zone List");

        PredefinedSearch.add(PSGlobal_Rad);
        PSGlobal_Rad.setText("Global Locations List");

        PredefinedSearch.add(PSMail_Rad);
        PSMail_Rad.setText("Mails List");

        SPSearch_bttn.setText("Search");
        SPSearch_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPSearch_bttnActionPerformed(evt);
            }
        });

        PredefinedSearch.add(PSPhone_Rad);
        PSPhone_Rad.setText("Agent Phones List");

        jLabel2.setText("Predefined Search");

        javax.swing.GroupLayout PSPaneLayout = new javax.swing.GroupLayout(PSPane);
        PSPane.setLayout(PSPaneLayout);
        PSPaneLayout.setHorizontalGroup(
            PSPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PSPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PSPaneLayout.createSequentialGroup()
                        .addGroup(PSPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PSCountry_Rad)
                            .addComponent(PSState_Rad)
                            .addComponent(PSZone_Rad)
                            .addComponent(PSGlobal_Rad)
                            .addComponent(PSMail_Rad)
                            .addComponent(PSPhone_Rad)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addGroup(PSPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SPSearch_bttn)))
                .addContainerGap())
        );
        PSPaneLayout.setVerticalGroup(
            PSPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSPaneLayout.createSequentialGroup()
                .addGroup(PSPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PSPaneLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PSCountry_Rad)
                        .addGap(32, 32, 32)
                        .addComponent(PSState_Rad)
                        .addGap(32, 32, 32)
                        .addComponent(PSZone_Rad)
                        .addGap(32, 32, 32)
                        .addComponent(PSGlobal_Rad)
                        .addGap(32, 32, 32)
                        .addComponent(PSMail_Rad)
                        .addGap(32, 32, 32)
                        .addComponent(PSPhone_Rad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PSPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(SPSearch_bttn)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Predefined Search", PSPane);

        add(jTabbedPane2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void SASearch_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SASearch_bttnActionPerformed
        // TODO add your handling code here:
        ArrayList fields = new ArrayList();
        if(SAid_Box.isSelected()){
            fields.add("ID");
        }
        if(SARole_Box.isSelected()){
            fields.add("Role");
        }
        if(SAName_Box.isSelected()){
            fields.add("Name");
        }
        if(SALastName_Box.isSelected()){
            fields.add("Last Name");
        }
        if(SANationalId_Box.isSelected()){
            fields.add("Natinal ID");
        }
        if(SABornDate_Box.isSelected()){
            fields.add("Born Date");
        }
        if(SAPhone_Box.isSelected()){
            fields.add("Phone");
        }
        if(SAMail_Box.isSelected()){
            fields.add("Mail");
        }
        if(SAEmergencyPhone_Box.isSelected()){
            fields.add("Emergency Phone");
        }
        if(SAHealth_Box.isSelected()){
            fields.add("Health Ensurance");
        }
        if(SACountry_Box.isSelected()){
            fields.add("Country");
        }
        if(SAState_Box.isSelected()){
            fields.add("State");
        }
        if(SAZone_Box.isSelected()){
            fields.add("Zone");
        }
        if(SAStreet_Box.isSelected()){
            fields.add("Street");
        }
        try{
            switch((String) SALook_Box.getSelectedItem()){
                case "all Agents":
                    imp.SearchAgents( SATable,fields);
                    break;
                case "ID":
                    imp.SearchID(Integer.parseInt(SAValue_txf.getText()), SATable,fields);
                    break;
                case "Role":
                    imp.SearchRole(SAValue_txf.getText(), SATable,fields);
                    break;
                case "Name":
                    imp.SearchName(SAValue_txf.getText(), SATable,fields);
                    break;
                /*case "Last Name":
                    imp.SearchLastName(SAValue_txf.getText(), SATable,fields);
                    break;*/
                case "National ID Number":
                    imp.SearchNational(SAValue_txf.getText(), SATable,fields);
                    break;
                /*case "Health Ensurance":
                    imp.SearchEnsurance(SAValue_txf.getText(), SATable,fields);
                    break;*/
                case "Phone Number":
                    imp.SearchPhone(SAValue_txf.getText(), SATable,fields);
                    break;
                /*case "Emergency Phone Number":
                    imp.SearchEmergency(SAValue_txf.getText(), SATable,fields);
                    break;*/
                case "Street":
                    imp.SearchAddress(SAValue_txf.getText(), SATable,fields);
                    break;  
                case "Mail":
                    imp.SearchMail(SAValue_txf.getText(), SATable,fields);
                    break;                  
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_SASearch_bttnActionPerformed

    private void SPSearch_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPSearch_bttnActionPerformed
        // TODO add your handling code here:
        try{
        if(this.PSCountry_Rad.isSelected()){
            String[] fields= {"Countrys"};
            imp.SearchCountrys( PSTable,fields);
        }else if(this.PSState_Rad.isSelected()){
            String[] fields= {"States"};
            imp.SearchStates(PSTable,fields);
        }else if(this.PSZone_Rad.isSelected()){
            String[] fields= {"Zone"};
            imp.SearchZones( PSTable,fields);
        }else if(this.PSGlobal_Rad.isSelected()){
            String[] fields= {"Country","State","Zone"};
            imp.SearchGlobalLocations( PSTable,fields);
        }else if(this.PSMail_Rad.isSelected()){
            String[] fields= {"Mail"};
            imp.SearchMails( PSTable,fields);
        }else if(this.PSPhone_Rad.isSelected()){
            String[] fields= {"Phone"};
            imp.SearchPhones( PSTable,fields);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_SPSearch_bttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GlobalSearch;
    private javax.swing.JRadioButton PSCountry_Rad;
    private javax.swing.JRadioButton PSGlobal_Rad;
    private javax.swing.JRadioButton PSMail_Rad;
    private javax.swing.JPanel PSPane;
    private javax.swing.JRadioButton PSPhone_Rad;
    private javax.swing.JRadioButton PSState_Rad;
    private javax.swing.JTable PSTable;
    private javax.swing.JRadioButton PSZone_Rad;
    private javax.swing.ButtonGroup PredefinedSearch;
    private javax.swing.JCheckBox SABornDate_Box;
    private javax.swing.JCheckBox SACountry_Box;
    private javax.swing.JCheckBox SAEmergencyPhone_Box;
    private javax.swing.JCheckBox SAHealth_Box;
    private javax.swing.JCheckBox SALastName_Box;
    private javax.swing.JComboBox<String> SALook_Box;
    private javax.swing.JCheckBox SAMail_Box;
    private javax.swing.JCheckBox SAName_Box;
    private javax.swing.JCheckBox SANationalId_Box;
    private javax.swing.JPanel SAPane;
    private javax.swing.JCheckBox SAPhone_Box;
    private javax.swing.JCheckBox SARole_Box;
    private javax.swing.JButton SASearch_bttn;
    private javax.swing.JCheckBox SAState_Box;
    private javax.swing.JCheckBox SAStreet_Box;
    private javax.swing.JTable SATable;
    private javax.swing.JTextField SAValue_txf;
    private javax.swing.JCheckBox SAZone_Box;
    private javax.swing.JCheckBox SAid_Box;
    private javax.swing.JButton SPSearch_bttn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
