/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uncuyo.dbproyect.OLDgui;
/**
 *
 * @author Martín
 */
public class GUIContainer extends javax.swing.JFrame {
    AgentsCUD CUD = new AgentsCUD();
    AgentsSearch AS = new AgentsSearch();
    OtherDataSearch ODS = new OtherDataSearch();
    Report REPORT = new Report();
    /**
     * Creates new form MainMenuGUI
     */
    public GUIContainer(){
        initComponents();
        bttBack.setVisible(false);
        bttAlert.setEnabled(false);
        this.bttGoOther.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        MenuPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttGoCUD = new javax.swing.JButton();
        bttGoSearch = new javax.swing.JButton();
        bttGoOther = new javax.swing.JButton();
        bttAlert = new javax.swing.JButton();
        bttGoReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackMenuPane = new javax.swing.JPanel();
        bttBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Martín Cogo Database Proyect");
        setBackground(new java.awt.Color(255, 102, 153));
        getContentPane().setLayout(new java.awt.CardLayout());

        Container.setAutoscrolls(true);
        Container.setOpaque(false);
        Container.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Menu");

        bttGoCUD.setText("Create,Delete & Update Agents");
        bttGoCUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGoCUDActionPerformed(evt);
            }
        });

        bttGoSearch.setText("Search Agents");
        bttGoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGoSearchActionPerformed(evt);
            }
        });

        bttGoOther.setText("Search Others");
        bttGoOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGoOtherActionPerformed(evt);
            }
        });

        bttAlert.setText("Alerts");

        bttGoReport.setText("Generate a Report");
        bttGoReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGoReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttGoReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttGoOther, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttGoSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttGoCUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttGoCUD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttGoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttGoOther, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttGoReport)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        MenuPane.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Alerts");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alert Type", "Agent ID", "TimeStamp"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        MenuPane.setRightComponent(jPanel2);

        Container.add(MenuPane, java.awt.BorderLayout.CENTER);

        BackMenuPane.setLayout(new java.awt.BorderLayout());

        bttBack.setText("Back");
        bttBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBackActionPerformed(evt);
            }
        });
        BackMenuPane.add(bttBack, java.awt.BorderLayout.LINE_END);

        Container.add(BackMenuPane, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Container, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttGoCUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGoCUDActionPerformed
        // TODO add your handling code here:
        MenuPane.setVisible(false);
        CUD.setVisible(true);
        Container.add(CUD);
        Container.validate();
       
        bttBack.setVisible(true);
        BackMenuPane.validate();
    }//GEN-LAST:event_bttGoCUDActionPerformed

    private void bttGoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGoSearchActionPerformed
        // TODO add your handling code here:
        MenuPane.setVisible(false);
        AS.setVisible(true);
        Container.add(AS);
        Container.validate();
        
        bttBack.setVisible(true);
        BackMenuPane.validate();
    }//GEN-LAST:event_bttGoSearchActionPerformed

    private void bttGoOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGoOtherActionPerformed
        // TODO add your handling code here:
        MenuPane.setVisible(false);
        ODS.setVisible(true);
        Container.add(ODS);
        Container.validate();
        
        bttBack.setVisible(true);
        BackMenuPane.validate();
    }//GEN-LAST:event_bttGoOtherActionPerformed

    private void bttGoReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGoReportActionPerformed
        // TODO add your handling code here:
        MenuPane.setVisible(false);
        REPORT.setVisible(true);
        Container.add(REPORT);
        Container.validate();
       
        bttBack.setVisible(true);
        BackMenuPane.validate();
    }//GEN-LAST:event_bttGoReportActionPerformed

    private void bttBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBackActionPerformed
        // TODO add your handling code here:
    GoBack();
    }//GEN-LAST:event_bttBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIContainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIContainer().setVisible(true);
            }
        });
    }
    
    public void GoBack(){
        bttBack.setVisible(false);
        CUD.setVisible(false);
        AS.setVisible(false);
        ODS.setVisible(false);
        REPORT.setVisible(false);
        MenuPane.setVisible(true);
        Container.add(MenuPane);
        Container.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackMenuPane;
    private javax.swing.JPanel Container;
    private javax.swing.JSplitPane MenuPane;
    private javax.swing.JButton bttAlert;
    private javax.swing.JButton bttBack;
    private javax.swing.JButton bttGoCUD;
    private javax.swing.JButton bttGoOther;
    private javax.swing.JButton bttGoReport;
    private javax.swing.JButton bttGoSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
