/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uncuyo.dbproyect.gui;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Martín
 */
public class PredefinedSearch extends javax.swing.JFrame {
    AgentsSearch_imp imp = new AgentsSearch_imp();
    /**
     * Creates new form PredefinedSearch
     */
    public PredefinedSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PSZone_Rad = new javax.swing.JRadioButton();
        PSGlobal_Rad = new javax.swing.JRadioButton();
        PSMail_Rad = new javax.swing.JRadioButton();
        SPSearch_bttn = new javax.swing.JButton();
        PSPhone_Rad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        PSCountry_Rad = new javax.swing.JRadioButton();
        PSState_Rad = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(PSZone_Rad);
        PSZone_Rad.setText("Zone List");

        buttonGroup1.add(PSGlobal_Rad);
        PSGlobal_Rad.setText("Global Locations List");

        buttonGroup1.add(PSMail_Rad);
        PSMail_Rad.setText("Mails List");

        SPSearch_bttn.setText("Search");
        SPSearch_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPSearch_bttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(PSPhone_Rad);
        PSPhone_Rad.setText("Agent Phones List");

        jLabel2.setText("Predefined Search");

        buttonGroup1.add(PSCountry_Rad);
        PSCountry_Rad.setText("Country List");

        buttonGroup1.add(PSState_Rad);
        PSState_Rad.setText("State List");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PSCountry_Rad)
                    .addComponent(PSState_Rad)
                    .addComponent(PSZone_Rad)
                    .addComponent(PSGlobal_Rad)
                    .addComponent(PSMail_Rad)
                    .addComponent(PSPhone_Rad)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SPSearch_bttn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PSCountry_Rad)
                .addGap(32, 32, 32)
                .addComponent(PSState_Rad)
                .addGap(32, 32, 32)
                .addComponent(PSZone_Rad)
                .addGap(32, 32, 32)
                .addComponent(PSGlobal_Rad)
                .addGap(32, 32, 32)
                .addComponent(PSMail_Rad)
                .addGap(32, 32, 32)
                .addComponent(PSPhone_Rad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPSearch_bttn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SPSearch_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPSearch_bttnActionPerformed
        // TODO add your handling code here:
        JTable table =PanelManager.view.getTable();
        try{
            if(this.PSCountry_Rad.isSelected()){
                String[] fields= {"Countrys"};
                imp.SearchCountrys(table,fields);
            }else if(this.PSState_Rad.isSelected()){
                String[] fields= {"States"};
                imp.SearchStates(table,fields);
            }else if(this.PSZone_Rad.isSelected()){
                String[] fields= {"Zone"};
                imp.SearchZones(table,fields);
            }else if(this.PSGlobal_Rad.isSelected()){
                String[] fields= {"Country","State","Zone"};
                imp.SearchGlobalLocations(table,fields);
            }else if(this.PSMail_Rad.isSelected()){
                String[] fields= {"Mail"};
                imp.SearchMails(table,fields);
            }else if(this.PSPhone_Rad.isSelected()){
                String[] fields= {"Phone"};
                imp.SearchPhones(table,fields);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_SPSearch_bttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelManager.predSearch.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton PSCountry_Rad;
    private javax.swing.JRadioButton PSGlobal_Rad;
    private javax.swing.JRadioButton PSMail_Rad;
    private javax.swing.JRadioButton PSPhone_Rad;
    private javax.swing.JRadioButton PSState_Rad;
    private javax.swing.JRadioButton PSZone_Rad;
    private javax.swing.JButton SPSearch_bttn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
