/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uncuyo.dbproyect.gui;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import uncuyo.dbproyect.domain.Date;
import uncuyo.dbproyect.domain.Mail;
import uncuyo.dbproyect.domain.PhoneNumber;
import uncuyo.dbproyect.gui.PanelManager;

/**
 *
 * @author Martín
 */
public class UpdatePanel extends javax.swing.JFrame {
    AgentsCUD_imp imp = new AgentsCUD_imp();
    /**
     * Creates new form NewJFrame1
     */
    public UpdatePanel() {
        initComponents();
        fillFields();
        UCountry_txf.setEnabled(false);
        UState_txf.setEnabled(false);
        UZone_txf.setEnabled(false);
        UName_txf.setEnabled(false);
        UCountry_Box.setEnabled(false);
        UState_Box.setEnabled(false);
        UZone_Box.setEnabled(false);
        ULastName_txf.setEnabled(false);
        UBornDate_formatted.setEnabled(false);
        this.UNationalNumber_formatted.setEnabled(false);
        this.URole_txf.setEnabled(false);
        this.URole_List.setEnabled(false);
        this.URole_Box.setEnabled(false);
        this.UCountry_List.setEnabled(false);
        this.UState_List.setEnabled(false);
        this.UZone_List.setEnabled(false);
        this.UStreet_txf.setEnabled(false);
        this.UNumber_txf.setEnabled(false);
        this.UHealthEnsurance_txf.setEnabled(false);
        this.UEmergencyPhone_formatted.setEnabled(false);
        this.UphoneNumber_formatted.setEnabled(false);
        this.Umail_formatted.setEnabled(false);
        
        imp.SetRoleComboBoxModel(URole_List);
        imp.SetCountryComboBoxModel(UCountry_List);
        imp.SetStateComboBoxModel(UState_List);
        imp.SetZoneComboBoxModel(UZone_List);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        UStreet_txf = new javax.swing.JTextField();
        UNumber_txf = new javax.swing.JTextField();
        UAddress_Box = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        UZone_List = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        UState_List = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        UCountry_List = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        UCountry_Box = new javax.swing.JCheckBox();
        UZone_Box = new javax.swing.JCheckBox();
        UState_Box = new javax.swing.JCheckBox();
        UCountry_txf = new javax.swing.JTextField();
        UState_txf = new javax.swing.JTextField();
        UZone_txf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        UName_txf = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        UBornDate_formatted = new javax.swing.JFormattedTextField();
        UNationalNumber_formatted = new javax.swing.JFormattedTextField();
        ULastName_txf = new javax.swing.JTextField();
        UName_Box = new javax.swing.JCheckBox();
        ULastName_Box = new javax.swing.JCheckBox();
        UBornDate_Box = new javax.swing.JCheckBox();
        UNationalID_Box = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        URole_Box = new javax.swing.JCheckBox();
        URole_List = new javax.swing.JComboBox<>();
        URole_txf = new javax.swing.JTextField();
        URole_Box2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        UStatus_txf = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        Uid_txf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Umail_formatted = new javax.swing.JFormattedTextField();
        UphoneNumber_formatted = new javax.swing.JFormattedTextField();
        UPhone_Box = new javax.swing.JCheckBox();
        UMail_Box = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        UHealthEnsurance_txf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        UEmergencyPhone_formatted = new javax.swing.JFormattedTextField();
        UEmergencyPhone_Box = new javax.swing.JCheckBox();
        UHealth_Box = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel26.setText("Live in Street ");

        UStreet_txf.setText("Main Street");

        UNumber_txf.setText("Number");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(3, 3, 3)
                .addComponent(UStreet_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UNumber_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UStreet_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UNumber_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(29, 29, 29))
        );

        UAddress_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UAddress_BoxActionPerformed(evt);
            }
        });

        UZone_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Godoy Cruz" }));

        jLabel8.setText("Zone:");

        UState_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mendoza" }));

        jLabel9.setText("State:");

        UCountry_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina" }));

        jLabel27.setText("Country:");

        UCountry_Box.setText("new Country");
        UCountry_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UCountry_BoxMousePressed(evt);
            }
        });

        UZone_Box.setText("new Zone");
        UZone_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UZone_BoxMousePressed(evt);
            }
        });

        UState_Box.setText("new State");
        UState_Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UState_BoxMousePressed(evt);
            }
        });

        UCountry_txf.setText("Argentina2");

        UState_txf.setText("Mendoza2");

        UZone_txf.setText("Godoy Cruz2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UCountry_Box))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(UCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UState_Box))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(UState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(UZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UZone_Box)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(UCountry_Box)
                    .addComponent(UZone_Box)
                    .addComponent(UState_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UCountry_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UState_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UZone_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UCountry_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UState_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UZone_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Data from Agent");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Last Name:");

        jLabel33.setText("Born Date:");

        jLabel34.setText("National ID:");

        UName_txf.setText("name");

        jLabel35.setText("Name:");

        UBornDate_formatted.setText("00/00/00");

        UNationalNumber_formatted.setText("43.222.222");

        ULastName_txf.setText("lastname");

        UName_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UName_BoxActionPerformed(evt);
            }
        });

        ULastName_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ULastName_BoxActionPerformed(evt);
            }
        });

        UBornDate_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBornDate_BoxActionPerformed(evt);
            }
        });

        UNationalID_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNationalID_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ULastName_txf)
                    .addComponent(UName_txf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UNationalNumber_formatted)
                    .addComponent(UBornDate_formatted, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(UNationalID_Box)
                    .addComponent(UBornDate_Box)
                    .addComponent(ULastName_Box)
                    .addComponent(UName_Box))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UName_Box, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(ULastName_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ULastName_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(UBornDate_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UNationalID_Box))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(UBornDate_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(UNationalNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        URole_Box.setText("Create new Role");
        URole_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URole_BoxActionPerformed(evt);
            }
        });

        URole_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        URole_txf.setText("new Role");

        URole_Box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URole_Box2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(URole_Box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URole_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(URole_Box2)
                .addGap(30, 30, 30))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(URole_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(URole_Box)
                .addComponent(URole_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(URole_Box2)
        );

        jLabel17.setText("Update by ID:");

        UStatus_txf.setText("-");

        jLabel36.setText("RESULT:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(UStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UStatus_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel22.setText("Phone number:");

        jLabel23.setText("Mail");

        Umail_formatted.setText("noseque@gmail.com");

        UphoneNumber_formatted.setText("2839289283");

        UPhone_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPhone_BoxActionPerformed(evt);
            }
        });

        UMail_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMail_BoxActionPerformed(evt);
            }
        });

        UHealthEnsurance_txf.setText("name");

        jLabel24.setText("Emergency Phone Number");

        jLabel25.setText("Health Ensurance Name");

        UEmergencyPhone_formatted.setText("92839283928");

        UEmergencyPhone_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UEmergencyPhone_BoxActionPerformed(evt);
            }
        });

        UHealth_Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UHealth_BoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(UHealthEnsurance_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(UEmergencyPhone_formatted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UEmergencyPhone_Box, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UHealth_Box, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(UHealthEnsurance_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UHealth_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(UEmergencyPhone_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UEmergencyPhone_Box))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(UphoneNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(Umail_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UPhone_Box)
                    .addComponent(UMail_Box)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(UphoneNumber_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UPhone_Box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Umail_formatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addComponent(UMail_Box)))
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Uid_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UAddress_Box))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Uid_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UAddress_Box))
                .addGap(8, 8, 8)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UAddress_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UAddress_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UAddress_Box.isSelected()){
            this.UCountry_List.setEnabled(true);
            this.UState_List.setEnabled(true);
            this.UZone_List.setEnabled(true);
            this.UStreet_txf.setEnabled(true);
            this.UNumber_txf.setEnabled(true);
            this.UCountry_Box.setEnabled(true);
            this.UState_Box.setEnabled(true);
            this.UZone_Box.setEnabled(true);
        }else{
            this.UCountry_List.setEnabled(false);
            this.UState_List.setEnabled(false);
            this.UZone_List.setEnabled(false);
            this.UStreet_txf.setEnabled(false);
            this.UNumber_txf.setEnabled(false);
            this.UCountry_Box.setEnabled(false);
            this.UState_Box.setEnabled(false);
            this.UZone_Box.setEnabled(false);
        }
    }//GEN-LAST:event_UAddress_BoxActionPerformed

    private void UCountry_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCountry_BoxMousePressed
        // TODO add your handling code here:
        if(UCountry_Box.isSelected()){
            UCountry_txf.setEnabled(false);
            UCountry_List.setEnabled(true);
            UZone_txf.setEnabled(false);
            UZone_List.setEnabled(true);
            UState_txf.setEnabled(false);
            UState_List.setEnabled(true);
        }else{
            UCountry_txf.setEnabled(true);
            UCountry_List.setEnabled(false);
            UZone_txf.setEnabled(true);
            UZone_List.setEnabled(false);
            UState_txf.setEnabled(true);
            UState_List.setEnabled(false);
        }
    }//GEN-LAST:event_UCountry_BoxMousePressed

    private void UZone_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UZone_BoxMousePressed
        // TODO add your handling code here:
        if(UZone_Box.isSelected()){
            UZone_txf.setEnabled(false);
            UZone_List.setEnabled(true);
        }else{
            UZone_txf.setEnabled(true);
            UZone_List.setEnabled(false);
        }
    }//GEN-LAST:event_UZone_BoxMousePressed

    private void UState_BoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UState_BoxMousePressed
        // TODO add your handling code here:
        if(UState_Box.isSelected()){
            UState_txf.setEnabled(false);
            UState_List.setEnabled(true);
            UZone_txf.setEnabled(false);
            UZone_List.setEnabled(true);
        }else{
            UState_txf.setEnabled(true);
            UState_List.setEnabled(false);
            UZone_txf.setEnabled(true);
            UZone_List.setEnabled(false);
        }
    }//GEN-LAST:event_UState_BoxMousePressed

    private void UName_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UName_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UName_Box.isSelected()){
            this.UName_txf.setEnabled(true);
        }else{
            UName_txf.setEnabled(false);
        }
    }//GEN-LAST:event_UName_BoxActionPerformed

    private void ULastName_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ULastName_BoxActionPerformed
        // TODO add your handling code here:
        if(this.ULastName_Box.isSelected()){
            this.ULastName_txf.setEnabled(true);
        }else{
            ULastName_txf.setEnabled(false);
        }
    }//GEN-LAST:event_ULastName_BoxActionPerformed

    private void UBornDate_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBornDate_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UBornDate_Box.isSelected()){
            this.UBornDate_formatted.setEnabled(true);
        }else{
            UBornDate_formatted.setEnabled(false);
        }
    }//GEN-LAST:event_UBornDate_BoxActionPerformed

    private void UNationalID_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNationalID_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UNationalID_Box.isSelected()){
            this.UNationalNumber_formatted.setEnabled(true);
        }else{
            UNationalNumber_formatted.setEnabled(false);
        }
    }//GEN-LAST:event_UNationalID_BoxActionPerformed

    private void URole_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URole_BoxActionPerformed
        // TODO add your handling code here:
        if(URole_Box.isSelected()){
            URole_txf.setEnabled(true);
            URole_List.setEnabled(false);
        }else{
            URole_txf.setEnabled(false);
            URole_List.setEnabled(true);
        }
    }//GEN-LAST:event_URole_BoxActionPerformed

    private void URole_Box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URole_Box2ActionPerformed
        // TODO add your handling code here:
        if(URole_Box2.isSelected()){
            this.URole_List.setEnabled(true);
            this.URole_txf.setEnabled(false);
            this.URole_Box.setEnabled(true);
        }else{
            this.URole_List.setEnabled(false);
            this.URole_txf.setEnabled(false);
            this.URole_Box.setEnabled(false);
        }
    }//GEN-LAST:event_URole_Box2ActionPerformed

    private void UPhone_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPhone_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UPhone_Box.isSelected()){
            this.UphoneNumber_formatted.setEnabled(true);
        }else{
            this.UphoneNumber_formatted.setEnabled(false);
        }
    }//GEN-LAST:event_UPhone_BoxActionPerformed

    private void UMail_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMail_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UMail_Box.isSelected()){
            this.Umail_formatted.setEnabled(true);
        }else{
            this.Umail_formatted.setEnabled(false);
        }
    }//GEN-LAST:event_UMail_BoxActionPerformed

    private void UEmergencyPhone_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UEmergencyPhone_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UEmergencyPhone_Box.isSelected()){
            this.UEmergencyPhone_formatted.setEnabled(true);
        }else{
            this.UEmergencyPhone_formatted.setEnabled(false);
        }
    }//GEN-LAST:event_UEmergencyPhone_BoxActionPerformed

    private void UHealth_BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UHealth_BoxActionPerformed
        // TODO add your handling code here:
        if(this.UHealth_Box.isSelected()){
            this.UHealthEnsurance_txf.setEnabled(true);
        }else{
            this.UHealthEnsurance_txf.setEnabled(false);
        }
    }//GEN-LAST:event_UHealth_BoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelManager.update.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          int id =Integer.parseInt(Uid_txf.getText());
        try{
            if(this.UName_Box.isSelected()){
                imp.UpdateName(id,UName_txf.getText());
            }
            if(this.ULastName_Box.isSelected()){
                imp.UpdateLastName(id,ULastName_txf.getText());
            }
            if(this.UBornDate_Box.isSelected()){
                imp.UpdateBornDate(id,new Date(UBornDate_formatted.getText()));
            }
            if(this.UNationalID_Box.isSelected()){
                imp.UpdateNationalNumber(id,this.UNationalNumber_formatted.getText());
            }
            if(URole_Box2.isSelected()){
                if(URole_Box.isSelected()){
                    imp.UpdateRole(id,this.URole_txf.getText());
                }else{
                    imp.UpdateRole(id,(String) URole_List.getSelectedItem());
                }
            }
            if(this.UAddress_Box.isSelected()){
                String country;
                String state;
                String zone;
                if(this.UCountry_Box.isSelected()){
                    country = this.UCountry_txf.getText();
                }else{
                    country = (String) this.UCountry_List.getSelectedItem();
                }
                if(this.UState_Box.isSelected()){
                   state = this.UState_txf.getText();
                }else{
                    state = (String) this.UState_List.getSelectedItem();
                }
                if(this.UZone_Box.isSelected()){
                    zone = this.UZone_txf.getText();
                }else{
                    zone = (String) this.UZone_List.getSelectedItem();
                }
                imp.UpdateAddress(id,country,state,zone,this.UStreet_txf.getText(),this.UNumber_txf.getText());
            }
            if(this.UHealth_Box.isSelected()){
                imp.UpdateHealth(id,UHealthEnsurance_txf.getText());
            }
            if(this.UEmergencyPhone_Box.isSelected()){
                imp.UpdateEmergencyPhone(id,new PhoneNumber(UEmergencyPhone_formatted.getText()));
            }
            if(this.UPhone_Box.isSelected()){
                imp.UpdatePhone(id,new PhoneNumber(UphoneNumber_formatted.getText()));
            }
            if(this.UMail_Box.isSelected()){
                imp.UpdateMail(id,new Mail(Umail_formatted.getText()));
            }
            UStatus_txf.setText("Succed.Agent Updated");
        }catch(Exception e){
            UStatus_txf.setText("Error.Agent Not Updated");
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void fillFields(){
        JTable table = PanelManager.view.getTable();
        int index = table.getSelectedRow();
        if(index>=0){
            int i = 0;
            for(Object item :PanelManager.view.fields){
                switch(item.toString()){
                    case "ID":{
                        Uid_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Name":{
                        UName_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Last Name":{
                        ULastName_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Born Date":{
                        UBornDate_formatted.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Natinal ID":{
                        this.UNationalNumber_formatted.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Role":{
                        URole_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Country":{
                        UCountry_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "State":{
                        UState_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Zone":{
                        UZone_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Street":{
                        UStreet_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }case "Health Ensurance":{
                        UHealthEnsurance_txf.setText(table.getValueAt(index,i).toString());
                        break;                
                    }
                    case "Emergency Phone":{
                        UEmergencyPhone_formatted.setText(table.getValueAt(index,i).toString());
                        break;                
                    }
                    case "Phone":{
                        UphoneNumber_formatted.setText(table.getValueAt(index,i).toString());
                        break;                
                    }
                    case "Mail":{
                        Umail_formatted.setText(table.getValueAt(index,i).toString());
                        break;                
                    }
                }
                i+=1;
            }
        }    
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox UAddress_Box;
    private javax.swing.JCheckBox UBornDate_Box;
    private javax.swing.JFormattedTextField UBornDate_formatted;
    private javax.swing.JCheckBox UCountry_Box;
    private javax.swing.JComboBox<String> UCountry_List;
    private javax.swing.JTextField UCountry_txf;
    private javax.swing.JCheckBox UEmergencyPhone_Box;
    private javax.swing.JFormattedTextField UEmergencyPhone_formatted;
    private javax.swing.JTextField UHealthEnsurance_txf;
    private javax.swing.JCheckBox UHealth_Box;
    private javax.swing.JCheckBox ULastName_Box;
    private javax.swing.JTextField ULastName_txf;
    private javax.swing.JCheckBox UMail_Box;
    private javax.swing.JCheckBox UName_Box;
    private javax.swing.JTextField UName_txf;
    private javax.swing.JCheckBox UNationalID_Box;
    private javax.swing.JFormattedTextField UNationalNumber_formatted;
    private javax.swing.JTextField UNumber_txf;
    private javax.swing.JCheckBox UPhone_Box;
    private javax.swing.JCheckBox URole_Box;
    private javax.swing.JCheckBox URole_Box2;
    private javax.swing.JComboBox<String> URole_List;
    private javax.swing.JTextField URole_txf;
    private javax.swing.JCheckBox UState_Box;
    private javax.swing.JComboBox<String> UState_List;
    private javax.swing.JTextField UState_txf;
    private javax.swing.JTextField UStatus_txf;
    private javax.swing.JTextField UStreet_txf;
    private javax.swing.JCheckBox UZone_Box;
    private javax.swing.JComboBox<String> UZone_List;
    private javax.swing.JTextField UZone_txf;
    private javax.swing.JTextField Uid_txf;
    private javax.swing.JFormattedTextField Umail_formatted;
    private javax.swing.JFormattedTextField UphoneNumber_formatted;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
