/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uncuyo.dbproyect.gui;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Martín
 */
public class ViewPanel extends javax.swing.JFrame {
    AgentsSearch_imp searchimp = new AgentsSearch_imp();
    Report_imp reportimp = new Report_imp();
    ArrayList fields;
    /**
     * Creates new form NewJFrame
     */
    public ViewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        SALook_Box = new javax.swing.JComboBox<>();
        SAName_Box = new javax.swing.JCheckBox();
        SAState_Box = new javax.swing.JCheckBox();
        SALastName_Box = new javax.swing.JCheckBox();
        SACountry_Box = new javax.swing.JCheckBox();
        register_bttn = new javax.swing.JButton();
        unsuscribe_bttn = new javax.swing.JButton();
        update_bttn = new javax.swing.JButton();
        SAEmergencyPhone_Box = new javax.swing.JCheckBox();
        SANationalId_Box = new javax.swing.JCheckBox();
        SAPhone_Box = new javax.swing.JCheckBox();
        SAHealth_Box = new javax.swing.JCheckBox();
        generateReport_bttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        RPath_txf = new javax.swing.JTextField();
        SAStreet_Box = new javax.swing.JCheckBox();
        SAZone_Box = new javax.swing.JCheckBox();
        SABornDate_Box = new javax.swing.JCheckBox();
        SARole_Box = new javax.swing.JCheckBox();
        SASearch_bttn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SATable = new javax.swing.JTable();
        SAid_Box = new javax.swing.JCheckBox();
        SAMail_Box = new javax.swing.JCheckBox();
        SAValue_txf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SALook_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all Agents", "ID", "Role", "Name", "National ID Number", "Street", "Phone Number", "Mail" }));

        SAName_Box.setText("Name");

        SAState_Box.setText("State");

        SALastName_Box.setText("Last Name");

        SACountry_Box.setText("Country");

        register_bttn.setText("Create new Agent");
        register_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_bttnActionPerformed(evt);
            }
        });

        unsuscribe_bttn.setText("Unsuscribe Agent");
        unsuscribe_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unsuscribe_bttnActionPerformed(evt);
            }
        });

        update_bttn.setText("Update Agent");
        update_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bttnActionPerformed(evt);
            }
        });

        SAEmergencyPhone_Box.setText("Emergency Phone");

        SANationalId_Box.setText("National ID");

        SAPhone_Box.setText("Phone");

        SAHealth_Box.setText("Health Ensurance Name");

        generateReport_bttn.setText("Generate Report");
        generateReport_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReport_bttnActionPerformed(evt);
            }
        });

        jLabel8.setText("Value:");

        RPath_txf.setText("C:\\Users\\Martín\\Desktop\\Ciencias en Computación\\report.pdf");

        SAStreet_Box.setText("Street");

        SAZone_Box.setText("Zone");

        SABornDate_Box.setText("Born Date");

        SARole_Box.setText("Role");

        SASearch_bttn.setText("Search");
        SASearch_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SASearch_bttnActionPerformed(evt);
            }
        });

        SATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(SATable);

        SAid_Box.setText("id");

        SAMail_Box.setText("Mail");

        jLabel6.setText("Look for:");

        jLabel7.setText("Show:");

        jToggleButton1.setText("Predefined Search");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RPath_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateReport_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SASearch_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(register_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unsuscribe_bttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAid_Box)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(SAName_Box)
                                .addComponent(SALastName_Box)
                                .addComponent(SARole_Box)
                                .addComponent(jLabel8)
                                .addComponent(SANationalId_Box)
                                .addComponent(SABornDate_Box)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SAZone_Box)
                                        .addComponent(SACountry_Box)
                                        .addComponent(SAState_Box)
                                        .addComponent(SAStreet_Box))
                                    .addGap(90, 90, 90)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SALook_Box, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SAValue_txf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAEmergencyPhone_Box, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAMail_Box, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SAHealth_Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SAPhone_Box, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SASearch_bttn)
                            .addComponent(generateReport_bttn)
                            .addComponent(RPath_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(register_bttn)
                            .addComponent(unsuscribe_bttn)
                            .addComponent(update_bttn)
                            .addComponent(jToggleButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SALook_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(SAValue_txf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAid_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SARole_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAName_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SALastName_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SABornDate_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SANationalId_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAPhone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAMail_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAEmergencyPhone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAHealth_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SACountry_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAState_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAZone_Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAStreet_Box)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SASearch_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SASearch_bttnActionPerformed
        // TODO add your handling code here:
        fields = new ArrayList();
        if(SAid_Box.isSelected()){
            fields.add("ID");
        }
        if(SARole_Box.isSelected()){
            fields.add("Role");
        }
        if(SAName_Box.isSelected()){
            fields.add("Name");
        }
        if(SALastName_Box.isSelected()){
            fields.add("Last Name");
        }
        if(SANationalId_Box.isSelected()){
            fields.add("Natinal ID");
        }
        if(SABornDate_Box.isSelected()){
            fields.add("Born Date");
        }
        if(SAPhone_Box.isSelected()){
            fields.add("Phone");
        }
        if(SAMail_Box.isSelected()){
            fields.add("Mail");
        }
        if(SAEmergencyPhone_Box.isSelected()){
            fields.add("Emergency Phone");
        }
        if(SAHealth_Box.isSelected()){
            fields.add("Health Ensurance");
        }
        if(SACountry_Box.isSelected()){
            fields.add("Country");
        }
        if(SAState_Box.isSelected()){
            fields.add("State");
        }
        if(SAZone_Box.isSelected()){
            fields.add("Zone");
        }
        if(SAStreet_Box.isSelected()){
            fields.add("Street");
        }
        try{
            switch((String) SALook_Box.getSelectedItem()){
                case "all Agents":
                searchimp.SearchAgents( SATable,fields);
                break;
                case "ID":
                searchimp.SearchID(Integer.parseInt(SAValue_txf.getText()), SATable,fields);
                break;
                case "Role":
                searchimp.SearchRole(SAValue_txf.getText(), SATable,fields);
                break;
                case "Name":
                searchimp.SearchName(SAValue_txf.getText(), SATable,fields);
                break;
                /*case "Last Name":
                imp.SearchLastName(SAValue_txf.getText(), SATable,fields);
                break;*/
                case "National ID Number":
                searchimp.SearchNational(SAValue_txf.getText(), SATable,fields);
                break;
                /*case "Health Ensurance":
                imp.SearchEnsurance(SAValue_txf.getText(), SATable,fields);
                break;*/
                case "Phone Number":
                searchimp.SearchPhone(SAValue_txf.getText(), SATable,fields);
                break;
                /*case "Emergency Phone Number":
                imp.SearchEmergency(SAValue_txf.getText(), SATable,fields);
                break;*/
                case "Street":
                searchimp.SearchAddress(SAValue_txf.getText(), SATable,fields);
                break;
                case "Mail":
                searchimp.SearchMail(SAValue_txf.getText(), SATable,fields);
                break;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_SASearch_bttnActionPerformed

    private void register_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_bttnActionPerformed
        // TODO add your handling code here:
        PanelManager.create.setVisible(true);
    }//GEN-LAST:event_register_bttnActionPerformed

    private void update_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bttnActionPerformed
        // TODO add your handling code here:
        PanelManager.update.fillFields();
        PanelManager.update.setVisible(true);
    }//GEN-LAST:event_update_bttnActionPerformed

    private void unsuscribe_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsuscribe_bttnActionPerformed
        // TODO add your handling code here:
        PanelManager.deregister.fillFields();
        PanelManager.deregister.setVisible(true);
    }//GEN-LAST:event_unsuscribe_bttnActionPerformed

    private void generateReport_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReport_bttnActionPerformed
        // TODO add your handling code here:
        String report;
        try{
            report = reportimp.getAgentsReport((DefaultTableModel) SATable.getModel());
            reportimp.SaveReport(report,RPath_txf.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(jDialog1, e.getMessage());
        }
    }//GEN-LAST:event_generateReport_bttnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        PanelManager.predSearch.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public JTable getTable(){
         return this.SATable;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RPath_txf;
    private javax.swing.JCheckBox SABornDate_Box;
    private javax.swing.JCheckBox SACountry_Box;
    private javax.swing.JCheckBox SAEmergencyPhone_Box;
    private javax.swing.JCheckBox SAHealth_Box;
    private javax.swing.JCheckBox SALastName_Box;
    private javax.swing.JComboBox<String> SALook_Box;
    private javax.swing.JCheckBox SAMail_Box;
    private javax.swing.JCheckBox SAName_Box;
    private javax.swing.JCheckBox SANationalId_Box;
    private javax.swing.JCheckBox SAPhone_Box;
    private javax.swing.JCheckBox SARole_Box;
    private javax.swing.JButton SASearch_bttn;
    private javax.swing.JCheckBox SAState_Box;
    private javax.swing.JCheckBox SAStreet_Box;
    private javax.swing.JTable SATable;
    private javax.swing.JTextField SAValue_txf;
    private javax.swing.JCheckBox SAZone_Box;
    private javax.swing.JCheckBox SAid_Box;
    private javax.swing.JButton generateReport_bttn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton register_bttn;
    private javax.swing.JButton unsuscribe_bttn;
    private javax.swing.JButton update_bttn;
    // End of variables declaration//GEN-END:variables
}
